# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e70b7bb8385ba2f799e571fc3ed0c26de6e059d93a5ca85a255daf4286dcded26ec421f6e2ea863ea9eefbfeec23270771848bae5d12239cac57522743ac29e4

test:
  secret_key_base: 1b6fbd0a57c1f2a05d2a989182c63e636c889ab1aa01bf31b449a658ddd915935174aeac66dfde808f9655138f8cbec98c39fa06931f695b57e487b39ad70f2f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
